version: '3.8'
services:

  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./src/main/resources/students.csv:/students.csv
      - ./src/main/resources/db/copy.sql:/docker-entrypoint-initdb.d/03_copy.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
#  tomcat:
#    container_name: tomcat_container
#    image: tomcat:9.0.82
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./target/web-app.war:/usr/local/tomcat/webapps/web-app.war
#    depends_on:
#      - postgres
#    networks:
#      - postgres
#    restart: unless-stopped
#  app:
#    image: app
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    restart: always

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: test@test.ru
#      PGADMIN_DEFAULT_PASSWORD: 123456
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "8081:80"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
